name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build DocFX site
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x
            8.x
      - name: Install DocFX
        run: |
          dotnet new tool-manifest
          dotnet tool install docfx
      - name: Run DocFX build
        run: |
          dotnet tool run docfx build docfx.local.json --verbose --debug --warningsAsErrors